-- SQL Schema Setup for Supabase Database
-- Run this code in your Supabase SQL Editor (https://supabase.com) to create the tables.

-- 1. Create product_likes table
create table if not exists public.product_likes (
  id uuid default gen_random_uuid() primary key,
  product_id text not null,
  user_ip text not null, -- Stores device ID or IP for identifying unique likes
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Prevent same device/IP from liking the same product more than once
  unique (product_id, user_ip)
);

-- Enable row level security (RLS) for product_likes
alter table public.product_likes enable row level security;

-- Create policies so anyone can view, add, or delete likes
create policy "Allow public read access on likes" 
on public.product_likes for select 
using (true);

create policy "Allow public insert access on likes" 
on public.product_likes for insert 
with check (true);

create policy "Allow public delete access on likes" 
on public.product_likes for delete 
using (true);


-- 2. Create product_reviews table
create table if not exists public.product_reviews (
  id bigint generated by default as identity primary key,
  product_id text not null,
  user_name text not null,
  rating integer not null check (rating >= 1 and rating <= 5),
  comment text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable row level security (RLS) for product_reviews
alter table public.product_reviews enable row level security;

-- Create policies so anyone can read and write reviews
create policy "Allow public read access on reviews" 
on public.product_reviews for select 
using (true);

create policy "Allow public insert access on reviews" 
on public.product_reviews for insert 
with check (true);
